import 'dotenv/config'

export const env = {
  MONGODB_URI: process.env.MONGODB_URI,
  MONGODB_URI_LOCAL: process.env.MONGODB_URI_LOCAL,
  ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  ACCESS_TOKEN_ADMIN_NAME: process.env.ACCESS_TOKEN_ADMIN_NAME,
  ACCESS_TOKEN_USER_NAME: process.env.ACCESS_TOKEN_USER_NAME,
  REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,
  REFRESH_TOKEN_ADMIN_NAME: process.env.REFRESH_TOKEN_ADMIN_NAME,
  REFRESH_TOKEN_USER_NAME: process.env.REFRESH_TOKEN_USER_NAME
}
